---
title: 'Task 2: Alignment'
author: "Dongyuan Wu"
date: '`r Sys.Date()`'
output:
  pdf_document: default
---

```{r, include=FALSE}

run <- c("SRR1554537", "SRR1554538", "SRR1554541", "SRR1554535", "SRR1554536",
         "SRR1554539")
isolate <- c("R3452", "R3462", "R3485", "R2869", "R3098", "R3467")
age <- c(-0.3836, -0.4027, -0.3836, 41.58, 44.17, 36.5)
sex <- c("female", "female", "male", "male", "female", "female")
race <- c("AA", "AA", "AA", "AA", "AA", "AA")
RIN <- c(9.6, 6.4, 5.7, 8.7, 5.3, 9)
sample <- c("fetal", "fetal", "fetal", "adult", "adult", "adult")
dat <- data.frame(run, isolate, age, sex, race, RIN, sample)
write.table(dat, "phenotype.txt", quote=FALSE, row.names=FALSE, sep="\t")

```

HISAT2 on Galaxy was used for alignment. There are totally 12 samples (6 fetal vs. 6 adult) available. However, due to the resource limitation, only half of them (3 fetal vs. 3 adult) were chosen to be analyzed.

## Fetal

### SRR1554537

55133946 reads; of these:

55133946 (100.00%) were paired; of these:

474170 (0.86%) aligned concordantly 0 times

52684816 (95.56%) aligned concordantly exactly 1 time

1974960 (3.58%) aligned concordantly >1 times

### SRR1554538

68026190 reads; of these:

68026190 (100.00%) were paired; of these:

549305 (0.81%) aligned concordantly 0 times

65058884 (95.64%) aligned concordantly exactly 1 time

2418001 (3.55%) aligned concordantly >1 times

### SRR1554541

69278357 reads; of these:

69278357 (100.00%) were paired; of these:

561488 (0.81%) aligned concordantly 0 times

66402692 (95.85%) aligned concordantly exactly 1 time

2314177 (3.34%) aligned concordantly >1 times

## Adult

### SRR1554535

38063721 reads; of these:

38063721 (100.00%) were paired; of these:

533477 (1.40%) aligned concordantly 0 times

36345262 (95.49%) aligned concordantly exactly 1 time

1184982 (3.11%) aligned concordantly >1 times

### SRR1554536

21450348 reads; of these:

21450348 (100.00%) were paired; of these:

141926 (0.66%) aligned concordantly 0 times

20543060 (95.77%) aligned concordantly exactly 1 time

765362 (3.57%) aligned concordantly >1 times

### SRR1554539

33742728 reads; of these:

33742728 (100.00%) were paired; of these:

503288 (1.49%) aligned concordantly 0 times

32420443 (96.08%) aligned concordantly exactly 1 time

818997 (2.43%) aligned concordantly >1 times